
# Configuración Oracle 
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

# Configuración Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Configuración del pool de conexiones
quarkus.datasource.jdbc.max-lifetime=${MAX_LIFETIME}
quarkus.datasource.jdbc.idle-removal-interval=${REMOVAL_INTERVAL}
quarkus.datasource.jdbc.min-size=${BD_MIN_SIZE}
quarkus.datasource.jdbc.max-size=${BD_MAX_SIZE}
quarkus.datasource.jdbc.acquisition-timeout=${ACQUISITION_TIMEOUT}